### ISSUE TITLE
Isn't stable

### ISSUE THREAD

**Issue by stefanpenner** [H1D/broccoli-wrap#2]
https://github.com/H1D/broccoli-wrap/blob/master/index.js#L1 should use broccoli-persistent-filter, this produces stable output and if wanted will also provided a persistent cache for faster initial builds

**Comment by H1D** [comment]
@stefanpenner is it a drop-in replacement? 
Touched this code 2.5 years ago, totally forgot how to test this 😆

**Comment by stefanpenner** [comment]
More or less. But ya tests may be a good thing. I don't have time this week, but I may be able to lend a hand next

**Comment by H1D** [comment]
Oh! I see you have good replacement. Added notice https://github.com/H1D/broccoli-wrap#this-repo-is-obsolete-use-map-from-stefanpennerbroccoli-stew-instead-how-to-reaplce-example-asakusumaember-rolluppull5files

**Comment by stefanpenner** [comment]
@H1D sounds totally reasonable. I didn't realize the `stew.map` could replace this until @rwjblue reminded me.
